import { useSession } from "next-auth/react";
import Head from "next/head";
import React from "react";
import Header from "~/components/Header";
import PostList from "~/components/PostList";

import { api } from "~/utils/api";

const Posts = () => {
  const { data: sessionData } = useSession();

  const deletePost = api.post.delete.useMutation({
    onSuccess: () => {
      void refetchPosts();
    },
  });

  const { data: posts, refetch: refetchPosts } = api.post.getUserPosts.useQuery(
    {
      userId: sessionData?.user.id ?? "",
    }
  );
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <article className="prose m-5 lg:prose-sm">
        <h1>Posts</h1>
        <div className="mx-5 flex flex-row gap-2">
          <PostList
            posts={posts}
            onDelete={(postId) => {
              deletePost.mutate({
                id: postId,
              });
            }}
            loading={deletePost.isLoading}
          />
        </div>
      </article>
    </>
  );
};

export default Posts;
