import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";
import Header from "~/components/Header";
import PostEditor from "~/components/PostEditor";

import { api } from "~/utils/api";

const Posts = () => {
  const router = useRouter();

  const createPost = api.post.create.useMutation({
    onSuccess: () => {
      void router.push("/posts");
    },
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <article className="prose m-5 lg:prose-sm">
        <h1>Add Post</h1>
        <PostEditor
          onSave={({ title, content, published }) => {
            void createPost.mutate({
              title,
              content,
              published,
            });
          }}
          loading={createPost.isLoading}
        />
      </article>
    </>
  );
};

export default Posts;
